services:
  api:
    container_name: my_market_api
    build: ./main_internet_magazine/.
    ports:
      - "8080:8080"
    environment:
      - LIQUIDBASE_DATASOURCE_URL=jdbc:postgresql://db:5432/shop
      - SPRING_DATASOURCE_URL=r2dbc:postgresql://db:5432/shop
      - SPRING_DATASOURCE_USERNAME=back
      - SPRING_DATASOURCE_PASSWORD=123
      - REDIS_DATASOURCE_URL=redis
      - URL_AUTH_PROVIDER = http://192.168.1.4:30238/realms/master
      - CLIENT_SECRET_CODE = I3jPV3KhJl2vkCW5qK9SwaAwz0PkY7rG
      - CLIENT_SECRET_ID = yandex-test
      - CLIENT_SECRET_PROVIDER = keycloak
    depends_on:
      - db
      - redis
  pay-service:
    container_name: pay-service
    build: ./pay_service/.
    ports:
      - "8081:8080"
  db:
    image: postgres
    container_name: db
    volumes:
      - /var/lib/postgresql
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=back
      - POSTGRES_PASSWORD=123
    #      - TZ=Asia/Yekaterinburg
  redis:
      image: redis:latest
      container_name: redis
      ports:
        - "6379:6379"
      volumes:
        - ./redisdata:/data
      environment:
        - REDIS_PASSWORD=123
        - REDIS_USER=user
        - REDIS_USER_PASSWORD=123