spring.application.name=my-market-app
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/shop
spring.r2dbc.username=back
spring.r2dbc.password=123
#spring.r2dbc.url=${SPRING_DATASOURCE_URL}
#spring.r2dbc.username=${SPRING_DATASOURCE_USERNAME}
#spring.r2dbc.password=${SPRING_DATASOURCE_PASSWORD}
#spring.r2dbc.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=public
spring.liquibase.enabled=true
spring.liquibase.url =jdbc:postgresql://localhost:5432/shop
spring.liquibase.user= back
spring.liquibase.password= 123
logging.level.org.springframework.web = trace
logging.level.org.springframework.r2dbc=TRACE

path.to.image = src\\main\\resources\\images

#spring.datasource.url=jdbc:postgresql://localhost:5432/shop
#spring.datasource.hikari.schema=public
#spring.datasource.username=back
#spring.datasource.password=123
#spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.api-docs.title=Pay service api
springdoc.api-docs.description=API ??? ?????????? ?????????
springdoc.api-docs.version=1.0.0 
# ???? ????????? UI
springdoc.swagger-ui.enabled=true
# ???? UI-?????
springdoc.swagger-ui.path=/swagger-ui-custom.html
# ???? ????????? ??????????? ?????????? ??????? ?? ????????
springdoc.swagger-ui.tryItOutEnabled=true
# ???? ????????? ?????????? ???????????
# ???? ????????, ??? ???????????? ??? ???????? ???????? ?????? ??????????? ?? ??????????
springdoc.swagger-ui.persistAuthorization=true 