spring.application.name=pay_service
springdoc.api-docs.title=Pay service api
springdoc.api-docs.description=API
springdoc.api-docs.version=1.0.0

springdoc.swagger-ui.enabled=true

springdoc.swagger-ui.path=/swagger-ui-custom.html

springdoc.swagger-ui.tryItOutEnabled=true

springdoc.swagger-ui.persistAuthorization=true