spring.application.name=my-market-app
#SPRING_DATASOURCE_URL=r2dbc:postgresql://localhost:5432/shop
#SPRING_DATASOURCE_USERNAME=back
#SPRING_DATASOURCE_PASSWORD=123
#REDIS_DATASOURCE_URL=localhost
#LIQUIDBASE_DATASOURCE_URL=jdbc:postgresql://localhost:5432/shop
#API_BASE_URL=http://localhost:8081
#URL_AUTH_PROVIDER = http://192.168.1.4:30238/realms/master
#CLIENT_SECRET_CODE = I3jPV3KhJl2vkCW5qK9SwaAwz0PkY7rG
#CLIENT_SECRET_ID = yandex-test
#CLIENT_SECRET_PROVIDER = keycloak
spring.r2dbc.url=${SPRING_DATASOURCE_URL}
spring.r2dbc.username=${SPRING_DATASOURCE_USERNAME}
spring.r2dbc.password=${SPRING_DATASOURCE_PASSWORD}
spring.r2dbc.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=public
spring.liquibase.enabled=true
spring.liquibase.url =${LIQUIDBASE_DATASOURCE_URL}
spring.liquibase.user= ${SPRING_DATASOURCE_USERNAME}
spring.liquibase.password= ${SPRING_DATASOURCE_PASSWORD}
logging.level.org.springframework.web = trace
logging.level.org.springframework.r2dbc=TRACE

path.to.image = src\\main\\resources\\images

#spring.datasource.url=jdbc:postgresql://localhost:5432/shop
#spring.datasource.hikari.schema=public
#spring.datasource.username=back
#spring.datasource.password=123
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.security.oauth2.client.registration.keycloak.provider=${CLIENT_SECRET_PROVIDER}
spring.security.oauth2.client.registration.keycloak.client-id=${CLIENT_SECRET_ID}
spring.security.oauth2.client.registration.keycloak.client-secret=${CLIENT_SECRET_CODE}
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.registration.keycloak.authorizationGrantType=authorization_code
spring.security.oauth2.client.provider.keycloak.issuer-uri= ${URL_AUTH_PROVIDER}
api.base.url=${API_BASE_URL}

spring.data.redis.host=${REDIS_DATASOURCE_URL}
spring.data.redis.port=6379
#spring.data.redis.username=${REDIS_USER}
#spring.data.redis.password=${REDIS_USER_PASSWORD}
spring.cache.cache-names=Item
